import type { Metadata } from "next";
import { Oswald, Josefin_Sans } from "next/font/google";
import "./globals.css";

// const oswald = Oswald({
//   variable: "--font-oswald",
//   subsets: ["latin"],
// });

// const josefinSans = Josefin_Sans({
//   variable: "--font-josefin-sans",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-background h-[4000px]`}
      >
        {children}
      </body>
    </html>
  );
}
