import type { Metadata } from "next";
import Nav from "@/components/nav/Nav";
import "./globals.css";
import { Providers } from "./providers";

import 'mapbox-gl/dist/mapbox-gl.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-background h-[4000px] text-primary font-sans antialiased">
        <Providers>
          <Nav />
          {children}
        </Providers>
      </body>
    </html>
  );
}
